services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
    restart: unless-stopped
    networks:
      - smartgates-network

  deepface:
    build:
      context: ./machine-learning-client
      dockerfile: Dockerfile
    container_name: deepface
    ports:
      - "5005:5005"
    restart: unless-stopped
    networks:
      - smartgates-network
    env_file:
      - ./machine-learning-client/.env
    depends_on:
      - mongodb

  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: web-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - smartgates-network
    env_file:
      - ./web-app/.env
    depends_on:
      - deepface

networks:
  smartgates-network:
    driver: bridge

volumes:
  mongodb-data:
