@BASE_URL=http://localhost:5005

### add face
# @name FACE
POST {{BASE_URL}}/faces
content-type: application/json

{
  "img": "",
  "name": ""
}

### verify face

POST {{BASE_URL}}/faces/verify
content-type: application/json

{
  "img": ""
}

### replace face

PUT {{BASE_URL}}/faces/{{FACE.response.body.$.face_id}}
content-type: application/json

{
  "img": "",
  "name": "John Doe"
}

### delete face

DELETE {{BASE_URL}}/faces/{{FACE.response.body.$.face_id}}
