name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        subdir: [web-app, machine-learning-client]

    steps:
      - uses: actions/checkout@v4

      - name: Install Python, pipenv, and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: "3.12.3"
          working-directory: ${{ matrix.subdir }}

      - name: Install Project Dependencies
        working-directory: ${{ matrix.subdir }}
        run: |
          pipenv install --dev

      - name: Test with pytest
        working-directory: ${{ matrix.subdir }}
        run: |
          pipenv run pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service: [web-app, deepface]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service == 'web-app' && 'web-app' || 'machine-learning-client' }}
          push: false
          load: true
          tags: ${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  compose-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup env files
        run: |
          echo "Creating .env files for services"
          chmod +x ./setup-env.sh
          ./setup-env.sh

      - name: Test docker-compose build
        run: |
          docker-compose build

      - name: Test docker-compose up
        run: |
          docker-compose up -d
          sleep 10
          docker-compose ps
          docker-compose down
