name: Machine Learning CI

on:
  push:
    paths:
      - "machine-learning-client/**"
  pull_request:
    paths:
      - "machine-learning-client/**"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        subdir: [machine-learning-client]

    steps:
      - uses: actions/checkout@v4

      - name: Install Python, pipenv, and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: "3.12.3"
          working-directory: ${{ matrix.subdir }}

      - name: Install Project Dependencies
        working-directory: ${{ matrix.subdir }}
        run: |
          pipenv install --dev

      - name: Test with pytest
        working-directory: ${{ matrix.subdir }}
        run: |
          pipenv run pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service: [deepface]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service == 'web-app' && 'web-app' || 'machine-learning-client' }}
          push: false
          load: true
          tags: ${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

