name: Machine Learning Client - Test Only

on:
  pull_request:
    paths:
      - "machine-learning-client/**"
  push:
    branches:
      - main
    paths:
      - "machine-learning-client/**"

jobs:
  test:
    name: Run Tests (machine-learning-client)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python, pipenv, and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: "3.12.3"
          working-directory: machine-learning-client

      - name: Install Dev Dependencies
        working-directory: machine-learning-client
        run: pipenv install --dev

      - name: Run Pytest
        working-directory: machine-learning-client
        run: pipenv run pytest
