name: Web App CI

on:
  pull_request:
    paths:
      - "web-app/**"
  push:
    branches:
      - main
    paths:
      - "web-app/**"

jobs:
  test:
    name: Run Tests (web-app)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python, pipenv, and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: "3.12.3"
          working-directory: web-app

      - name: Install Dev Dependencies
        working-directory: web-app
        run: pipenv install --dev

      - name: Run Pytest
        working-directory: web-app
        run: pipenv run pytest

  build:
    name: Build Docker Image (web-app)
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: web-app
          push: false
          load: true
          tags: web-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

